// Chinese 1 Words - 12과 단어 데이터
const WORD_LESSONS = [
    {
        id: 1,
        title: "你好！",
        titlePinyin: "Nǐ hǎo!",
        titleKr: "안녕하세요!",
        words: [
            { chinese: "老师", pinyin: "lǎoshī", korean: "선생님, 스승", english: "teacher", pos: "명" },
            { chinese: "您", pinyin: "nín", korean: "당신(높임)", english: "you (formal)", pos: "대" },
            { chinese: "好", pinyin: "hǎo", korean: "좋다, 안녕하다", english: "good, well", pos: "형" },
            { chinese: "你", pinyin: "nǐ", korean: "너, 당신", english: "you", pos: "대" },
            { chinese: "再见", pinyin: "zàijiàn", korean: "또 만나요, 안녕히", english: "goodbye", pos: "동" },
            { chinese: "明天", pinyin: "míngtiān", korean: "내일", english: "tomorrow", pos: "명" },
            { chinese: "吗", pinyin: "ma", korean: "~인가요? (의문)", english: "(question particle)", pos: "조" },
            { chinese: "我", pinyin: "wǒ", korean: "나, 저", english: "I, me", pos: "대" },
            { chinese: "很", pinyin: "hěn", korean: "매우, 아주", english: "very", pos: "부" },
            { chinese: "最近", pinyin: "zuìjìn", korean: "최근, 요즘", english: "recently", pos: "명" },
            { chinese: "忙", pinyin: "máng", korean: "바쁘다", english: "busy", pos: "형" },
            { chinese: "不", pinyin: "bù", korean: "아니다, ~않다", english: "not", pos: "부" }
        ]
    },
    {
        id: 2,
        title: "我是学生。",
        titlePinyin: "Wǒ shì xuésheng.",
        titleKr: "나는 학생이야.",
        words: [
            { chinese: "是", pinyin: "shì", korean: "~이다", english: "to be", pos: "동" },
            { chinese: "学生", pinyin: "xuésheng", korean: "학생", english: "student", pos: "명" },
            { chinese: "呢", pinyin: "ne", korean: "~는? (생략의문)", english: "(question particle)", pos: "조" },
            { chinese: "也", pinyin: "yě", korean: "~도, 또한", english: "also, too", pos: "부" },
            { chinese: "请问", pinyin: "qǐngwèn", korean: "말씀 좀 여쭙겠습니다", english: "excuse me, may I ask", pos: "동" },
            { chinese: "这", pinyin: "zhè", korean: "이, 이것", english: "this", pos: "대" },
            { chinese: "汉语", pinyin: "Hànyǔ", korean: "중국어", english: "Chinese language", pos: "명" },
            { chinese: "书", pinyin: "shū", korean: "책", english: "book", pos: "명" },
            { chinese: "服务员", pinyin: "fúwùyuán", korean: "종업원", english: "waiter, waitress", pos: "명" },
            { chinese: "不是", pinyin: "búshì", korean: "~이 아니다", english: "is not", pos: "동" },
            { chinese: "词典", pinyin: "cídiǎn", korean: "사전", english: "dictionary", pos: "명" },
            { chinese: "那", pinyin: "nà", korean: "그, 저것", english: "that", pos: "대" },
            { chinese: "什么", pinyin: "shénme", korean: "무엇, 무슨", english: "what", pos: "대" },
            { chinese: "谢谢", pinyin: "xièxie", korean: "감사합니다", english: "thank you", pos: "동" },
            { chinese: "不客气", pinyin: "búkèqi", korean: "별말씀을요", english: "you're welcome", pos: "형" },
            { chinese: "朋友", pinyin: "péngyou", korean: "친구", english: "friend", pos: "명" },
            { chinese: "他", pinyin: "tā", korean: "그, 그 사람", english: "he, him", pos: "대" },
            { chinese: "她", pinyin: "tā", korean: "그녀", english: "she, her", pos: "대" }
        ]
    },
    {
        id: 3,
        title: "我叫朴海镇。",
        titlePinyin: "Wǒ jiào Piáo Hǎizhèn.",
        titleKr: "나는 박해진이라고 불러.",
        words: [
            { chinese: "叫", pinyin: "jiào", korean: "(~라고) 부르다", english: "to be called", pos: "동" },
            { chinese: "名字", pinyin: "míngzi", korean: "이름, 성명", english: "name", pos: "명" },
            { chinese: "姓", pinyin: "xìng", korean: "성이 ~이다", english: "surname", pos: "동" },
            { chinese: "认识", pinyin: "rènshi", korean: "알다, 인식하다", english: "to know, to recognize", pos: "동" },
            { chinese: "高兴", pinyin: "gāoxìng", korean: "기쁘다, 즐겁다", english: "happy, glad", pos: "형" },
            { chinese: "哪", pinyin: "nǎ", korean: "어느", english: "which", pos: "대" },
            { chinese: "国", pinyin: "guó", korean: "국가, 나라", english: "country, nation", pos: "명" },
            { chinese: "人", pinyin: "rén", korean: "사람", english: "person, people", pos: "명" },
            { chinese: "中国人", pinyin: "Zhōngguórén", korean: "중국인", english: "Chinese person", pos: "명" },
            { chinese: "韩国人", pinyin: "Hánguórén", korean: "한국인", english: "Korean person", pos: "명" },
            { chinese: "对", pinyin: "duì", korean: "맞다, 옳다", english: "correct, right", pos: "형" },
            { chinese: "我们", pinyin: "wǒmen", korean: "우리(들)", english: "we, us", pos: "대" },
            { chinese: "都", pinyin: "dōu", korean: "모두, 다", english: "all, both", pos: "부" },
            { chinese: "留学生", pinyin: "liúxuéshēng", korean: "유학생", english: "international student", pos: "명" }
        ]
    },
    {
        id: 4,
        title: "我在学校。",
        titlePinyin: "Wǒ zài xuéxiào.",
        titleKr: "나는 학교에 있어.",
        words: [
            { chinese: "在", pinyin: "zài", korean: "~에 있다, ~에서", english: "at, in (location)", pos: "동" },
            { chinese: "哪儿", pinyin: "nǎr", korean: "어디", english: "where", pos: "대" },
            { chinese: "学校", pinyin: "xuéxiào", korean: "학교", english: "school", pos: "명" },
            { chinese: "家", pinyin: "jiā", korean: "집", english: "home, family", pos: "명" },
            { chinese: "做", pinyin: "zuò", korean: "~을 하다", english: "to do, to make", pos: "동" },
            { chinese: "学习", pinyin: "xuéxí", korean: "공부하다, 배우다", english: "to study, to learn", pos: "동" },
            { chinese: "图书馆", pinyin: "túshūguǎn", korean: "도서관", english: "library", pos: "명" },
            { chinese: "看", pinyin: "kàn", korean: "보다", english: "to see, to watch", pos: "동" },
            { chinese: "电视", pinyin: "diànshì", korean: "텔레비전", english: "television, TV", pos: "명" },
            { chinese: "作业", pinyin: "zuòyè", korean: "숙제", english: "homework", pos: "명" },
            { chinese: "现在", pinyin: "xiànzài", korean: "현재, 지금", english: "now, at present", pos: "부" }
        ]
    },
    {
        id: 5,
        title: "我家有三口人。",
        titlePinyin: "Wǒ jiā yǒu sān kǒu rén.",
        titleKr: "우리 집은 가족이 세 명이야.",
        words: [
            { chinese: "有", pinyin: "yǒu", korean: "있다, 가지고 있다", english: "to have, there is", pos: "동" },
            { chinese: "几", pinyin: "jǐ", korean: "몇", english: "how many (under 10)", pos: "수" },
            { chinese: "口", pinyin: "kǒu", korean: "식구(양사)", english: "(measure word for family)", pos: "양" },
            { chinese: "爸爸", pinyin: "bàba", korean: "아빠, 아버지", english: "dad, father", pos: "명" },
            { chinese: "妈妈", pinyin: "māma", korean: "엄마, 어머니", english: "mom, mother", pos: "명" },
            { chinese: "和", pinyin: "hé", korean: "~과(와)", english: "and, with", pos: "개" },
            { chinese: "没有", pinyin: "méiyǒu", korean: "없다, 갖고 있지 않다", english: "to not have", pos: "동" },
            { chinese: "兄弟姐妹", pinyin: "xiōngdì jiěmèi", korean: "형제자매", english: "siblings", pos: "명" },
            { chinese: "哥哥", pinyin: "gēge", korean: "형, 오빠", english: "older brother", pos: "명" },
            { chinese: "工作", pinyin: "gōngzuò", korean: "일, 일하다", english: "work, job", pos: "명" },
            { chinese: "医院", pinyin: "yīyuàn", korean: "병원", english: "hospital", pos: "명" },
            { chinese: "个", pinyin: "gè", korean: "개(양사)", english: "(general measure word)", pos: "양" },
            { chinese: "姐姐", pinyin: "jiějie", korean: "누나, 언니", english: "older sister", pos: "명" },
            { chinese: "空中小姐", pinyin: "kōngzhōng xiǎojiě", korean: "여승무원", english: "flight attendant", pos: "명" },
            { chinese: "医生", pinyin: "yīshēng", korean: "의사", english: "doctor", pos: "명" },
            { chinese: "北京大学", pinyin: "Běijīng Dàxué", korean: "베이징 대학교", english: "Peking University", pos: "명" },
            { chinese: "弟弟", pinyin: "dìdi", korean: "남동생", english: "younger brother", pos: "명" },
            { chinese: "妹妹", pinyin: "mèimei", korean: "여동생", english: "younger sister", pos: "명" }
        ]
    },
    {
        id: 6,
        title: "现在九点。",
        titlePinyin: "Xiànzài jiǔ diǎn.",
        titleKr: "지금은 9시야.",
        words: [
            { chinese: "几点", pinyin: "jǐ diǎn", korean: "몇 시", english: "what time", pos: "명" },
            { chinese: "上课", pinyin: "shàngkè", korean: "수업을 듣다", english: "to attend class", pos: "동" },
            { chinese: "半", pinyin: "bàn", korean: "30분, 절반", english: "half", pos: "명" },
            { chinese: "下午", pinyin: "xiàwǔ", korean: "오후", english: "afternoon", pos: "명" },
            { chinese: "星期几", pinyin: "xīngqī jǐ", korean: "무슨 요일", english: "what day of the week", pos: "명" },
            { chinese: "星期二", pinyin: "xīngqī'èr", korean: "화요일", english: "Tuesday", pos: "명" },
            { chinese: "那么", pinyin: "nà(me)", korean: "그럼, 그렇다면", english: "then, in that case", pos: "접" },
            { chinese: "一起", pinyin: "yìqǐ", korean: "함께, 같이", english: "together", pos: "부" },
            { chinese: "去", pinyin: "qù", korean: "가다", english: "to go", pos: "동" },
            { chinese: "来", pinyin: "lái", korean: "오다", english: "to come", pos: "동" },
            { chinese: "书店", pinyin: "shūdiàn", korean: "서점", english: "bookstore", pos: "명" },
            { chinese: "差", pinyin: "chà", korean: "부족하다, 모자라다", english: "short of, lacking", pos: "형" },
            { chinese: "一刻", pinyin: "yíkè", korean: "15분", english: "quarter (of an hour)", pos: "명" },
            { chinese: "美国人", pinyin: "Měiguórén", korean: "미국인", english: "American", pos: "명" },
            { chinese: "星期一", pinyin: "xīngqīyī", korean: "월요일", english: "Monday", pos: "명" }
        ]
    },
    {
        id: 7,
        title: "我今年二十岁。",
        titlePinyin: "Wǒ jīnnián èrshí suì.",
        titleKr: "나는 올해 20살이야.",
        words: [
            { chinese: "今年", pinyin: "jīnnián", korean: "올해, 금년", english: "this year", pos: "명" },
            { chinese: "多大", pinyin: "duōdà", korean: "(나이가) 얼마인가", english: "how old", pos: "형" },
            { chinese: "岁", pinyin: "suì", korean: "세, 살", english: "years old", pos: "양" },
            { chinese: "的", pinyin: "de", korean: "~의 (관형격)", english: "(possessive particle)", pos: "조" },
            { chinese: "生日", pinyin: "shēngrì", korean: "생일", english: "birthday", pos: "명" },
            { chinese: "月", pinyin: "yuè", korean: "월, 달", english: "month", pos: "명" },
            { chinese: "号", pinyin: "hào", korean: "일, 날짜", english: "date, number", pos: "명" },
            { chinese: "奶奶", pinyin: "nǎinai", korean: "할머니", english: "grandmother (paternal)", pos: "명" },
            { chinese: "时间", pinyin: "shíjiān", korean: "시간", english: "time", pos: "명" },
            { chinese: "事", pinyin: "shì", korean: "일, 사건", english: "matter, thing", pos: "명" },
            { chinese: "吃饭", pinyin: "chīfàn", korean: "밥을 먹다", english: "to eat (a meal)", pos: "동" },
            { chinese: "吧", pinyin: "ba", korean: "~하자 (청유)", english: "(suggestion particle)", pos: "조" },
            { chinese: "饭店", pinyin: "fàndiàn", korean: "호텔, 식당", english: "hotel, restaurant", pos: "명" }
        ]
    },
    {
        id: 8,
        title: "我想吃中国菜。",
        titlePinyin: "Wǒ xiǎng chī Zhōngguó cài.",
        titleKr: "나는 중국 음식을 먹고 싶어.",
        words: [
            { chinese: "饿", pinyin: "è", korean: "배고프다", english: "hungry", pos: "형" },
            { chinese: "想", pinyin: "xiǎng", korean: "~하고 싶다", english: "to want, to think", pos: "조동" },
            { chinese: "中国菜", pinyin: "Zhōngguó cài", korean: "중국 음식, 중국 요리", english: "Chinese food", pos: "명" },
            { chinese: "走", pinyin: "zǒu", korean: "가다, 걷다", english: "to walk, to go", pos: "동" },
            { chinese: "喜欢", pinyin: "xǐhuan", korean: "좋아하다", english: "to like", pos: "동" },
            { chinese: "锅包肉", pinyin: "guōbāoròu", korean: "찹쌀탕수육, 꿔바오러우", english: "sweet and sour pork", pos: "명" },
            { chinese: "听说", pinyin: "tīngshuō", korean: "듣자하니, 듣건대", english: "heard that, it is said", pos: "동" },
            { chinese: "食堂", pinyin: "shítáng", korean: "구내식당", english: "cafeteria, canteen", pos: "명" },
            { chinese: "铁板牛肉", pinyin: "tiěbǎn niúròu", korean: "철판소고기볶음", english: "sizzling beef", pos: "명" },
            { chinese: "好吃", pinyin: "hǎochī", korean: "맛있다", english: "delicious", pos: "형" },
            { chinese: "尝尝", pinyin: "chángchang", korean: "맛보다, 한번 먹어보다", english: "to taste, to try", pos: "동" },
            { chinese: "下课", pinyin: "xiàkè", korean: "수업을 마치다", english: "class ends, after class", pos: "동" },
            { chinese: "以后", pinyin: "yǐhòu", korean: "이후, ~후에", english: "after, later", pos: "명" },
            { chinese: "决定", pinyin: "juédìng", korean: "결정하다", english: "to decide", pos: "동" }
        ]
    },
    {
        id: 9,
        title: "你最近怎么样？",
        titlePinyin: "Nǐ zuìjìn zěnmeyàng?",
        titleKr: "너는 요즘 어때?",
        words: [
            { chinese: "怎么样", pinyin: "zěnmeyàng", korean: "어떻다, 어떠하다", english: "how is it, how about", pos: "대" },
            { chinese: "准备", pinyin: "zhǔnbèi", korean: "준비하다", english: "to prepare", pos: "동" },
            { chinese: "考试", pinyin: "kǎoshì", korean: "시험", english: "exam, test", pos: "명" },
            { chinese: "太", pinyin: "tài", korean: "너무, 매우", english: "too, extremely", pos: "부" },
            { chinese: "难", pinyin: "nán", korean: "어렵다, 힘들다", english: "difficult, hard", pos: "형" },
            { chinese: "了", pinyin: "le", korean: "~했다 (완료/감탄)", english: "(particle)", pos: "조" },
            { chinese: "件", pinyin: "jiàn", korean: "벌 (옷 양사)", english: "(measure word for clothes)", pos: "양" },
            { chinese: "衣服", pinyin: "yīfu", korean: "옷, 의복", english: "clothes, clothing", pos: "명" },
            { chinese: "好看", pinyin: "hǎokàn", korean: "예쁘다, 보기 좋다", english: "good-looking", pos: "형" },
            { chinese: "可是", pinyin: "kěshì", korean: "그러나, 하지만", english: "but, however", pos: "접" },
            { chinese: "有点儿", pinyin: "yǒudiǎnr", korean: "조금, 약간", english: "a little, somewhat", pos: "부" },
            { chinese: "大", pinyin: "dà", korean: "크다, 넓다", english: "big, large", pos: "형" },
            { chinese: "小", pinyin: "xiǎo", korean: "작다, 적다", english: "small, little", pos: "형" },
            { chinese: "一点儿", pinyin: "yìdiǎnr", korean: "조금, 약간", english: "a little bit", pos: "양" },
            { chinese: "合适", pinyin: "héshì", korean: "적당하다, 알맞다", english: "suitable, appropriate", pos: "형" },
            { chinese: "正", pinyin: "zhèng", korean: "딱, 마침", english: "just, exactly", pos: "부" },
            { chinese: "颜色", pinyin: "yánsè", korean: "색, 색깔", english: "color", pos: "명" },
            { chinese: "不错", pinyin: "búcuò", korean: "괜찮다, 좋다", english: "not bad, pretty good", pos: "형" },
            { chinese: "就", pinyin: "jiù", korean: "바로, 곧", english: "just, then", pos: "부" },
            { chinese: "买", pinyin: "mǎi", korean: "사다", english: "to buy", pos: "동" },
            { chinese: "试试", pinyin: "shìshi", korean: "시험삼아 해보다", english: "to try", pos: "동" }
        ]
    },
    {
        id: 10,
        title: "周末你做什么了？",
        titlePinyin: "Zhōumò nǐ zuò shénme le?",
        titleKr: "주말에 너는 무엇을 했어?",
        words: [
            { chinese: "打算", pinyin: "dǎsuan", korean: "~할 예정이다", english: "to plan, to intend", pos: "동" },
            { chinese: "回家", pinyin: "huíjiā", korean: "집으로 돌아가다", english: "to go home", pos: "동" },
            { chinese: "休息", pinyin: "xiūxi", korean: "휴식하다", english: "to rest", pos: "동" },
            { chinese: "周末", pinyin: "zhōumò", korean: "주말", english: "weekend", pos: "명" },
            { chinese: "还", pinyin: "hái", korean: "아직, 그리고, 게다가", english: "still, also, in addition", pos: "부" },
            { chinese: "知道", pinyin: "zhīdào", korean: "알다", english: "to know", pos: "동" },
            { chinese: "跟", pinyin: "gēn", korean: "~와(과)", english: "with, and", pos: "개" },
            { chinese: "逛街", pinyin: "guàngjiē", korean: "거리를 구경하다", english: "to go window shopping", pos: "동" },
            { chinese: "好玩儿", pinyin: "hǎowánr", korean: "재미있다, 놀기 좋다", english: "fun, interesting", pos: "형" },
            { chinese: "那边", pinyin: "nàbiān", korean: "그쪽, 저쪽", english: "over there", pos: "대" },
            { chinese: "小店", pinyin: "xiǎodiàn", korean: "작은 가게, 작은 상점", english: "small shop", pos: "명" },
            { chinese: "餐厅", pinyin: "cāntīng", korean: "레스토랑, 식당", english: "restaurant", pos: "명" }
        ]
    },
    {
        id: 11,
        title: "我去过故宫。",
        titlePinyin: "Wǒ qùguo Gùgōng.",
        titleKr: "나는 고궁에 가 본 적이 있어.",
        words: [
            { chinese: "过", pinyin: "guo", korean: "~한 적이 있다 (경험)", english: "(experience particle)", pos: "조" },
            { chinese: "故宫", pinyin: "Gùgōng", korean: "고궁 (자금성)", english: "Forbidden City", pos: "고유" },
            { chinese: "当然", pinyin: "dāngrán", korean: "당연하다, 물론이다", english: "of course", pos: "부" },
            { chinese: "漂亮", pinyin: "piàoliang", korean: "예쁘다, 아름답다", english: "beautiful, pretty", pos: "형" },
            { chinese: "极", pinyin: "jí", korean: "극도로, 최고로", english: "extremely", pos: "부" },
            { chinese: "上午", pinyin: "shàngwǔ", korean: "오전", english: "morning, AM", pos: "명" },
            { chinese: "没问题", pinyin: "méi wèntí", korean: "문제없다", english: "no problem", pos: "동" },
            { chinese: "哪些", pinyin: "nǎxiē", korean: "어떤 ~들 (복수)", english: "which ones", pos: "대" },
            { chinese: "地方", pinyin: "dìfang", korean: "곳, 장소", english: "place", pos: "명" },
            { chinese: "颐和园", pinyin: "Yíhéyuán", korean: "이화원 (이허위안)", english: "Summer Palace", pos: "고유" },
            { chinese: "北海公园", pinyin: "Běihǎi Gōngyuán", korean: "북해공원", english: "Beihai Park", pos: "고유" },
            { chinese: "八达岭", pinyin: "Bādálǐng", korean: "팔달령 (빠다링)", english: "Badaling (Great Wall)", pos: "고유" },
            { chinese: "陪", pinyin: "péi", korean: "동반하다, 모시다", english: "to accompany", pos: "동" },
            { chinese: "昨天", pinyin: "zuótiān", korean: "어제", english: "yesterday", pos: "명" },
            { chinese: "不过", pinyin: "búguò", korean: "그러나, 하지만", english: "however, but", pos: "접" }
        ]
    },
    {
        id: 12,
        title: "他会说汉语。",
        titlePinyin: "Tā huì shuō Hànyǔ.",
        titleKr: "그는 중국어를 말할 수 있어.",
        words: [
            { chinese: "同屋", pinyin: "tóngwū", korean: "룸메이트", english: "roommate", pos: "명" },
            { chinese: "会", pinyin: "huì", korean: "~할 수 있다", english: "can, able to", pos: "조동" },
            { chinese: "说", pinyin: "shuō", korean: "말하다", english: "to speak, to say", pos: "동" },
            { chinese: "但是", pinyin: "dànshì", korean: "그러나, 그렇지만", english: "but, however", pos: "접" },
            { chinese: "不太", pinyin: "bútài", korean: "그다지 ~않다, 별로", english: "not very, not too", pos: "부" },
            { chinese: "怎么", pinyin: "zěnme", korean: "어떻게, 왜", english: "how, why", pos: "대" },
            { chinese: "交流", pinyin: "jiāoliú", korean: "교류하다, 소통하다", english: "to communicate", pos: "동" },
            { chinese: "有时候", pinyin: "yǒushíhou", korean: "때때로, 때로는", english: "sometimes", pos: "부" },
            { chinese: "英语", pinyin: "Yīngyǔ", korean: "영어", english: "English language", pos: "명" },
            { chinese: "唱歌", pinyin: "chànggē", korean: "노래를 부르다", english: "to sing", pos: "동" },
            { chinese: "只", pinyin: "zhǐ", korean: "오직, 다만", english: "only, just", pos: "부" },
            { chinese: "首", pinyin: "shǒu", korean: "곡 (양사)", english: "(measure word for songs)", pos: "양" },
            { chinese: "放假", pinyin: "fàngjià", korean: "방학하다, 쉬다", english: "to have vacation", pos: "동" },
            { chinese: "要", pinyin: "yào", korean: "~하려고 하다", english: "to want, to need", pos: "조동" },
            { chinese: "学", pinyin: "xué", korean: "배우다, 공부하다", english: "to learn, to study", pos: "동" },
            { chinese: "帮", pinyin: "bāng", korean: "돕다, 거들다", english: "to help", pos: "동" },
            { chinese: "就是", pinyin: "jiùshì", korean: "~뿐이다, ~밖에 안 된다", english: "just, only", pos: "부" }
        ]
    }
];
